# Generated by Django 6.0.2 on 2026-03-12 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=255)),
                ('id_no', models.CharField(max_length=255)),
                ('grade', models.IntegerField()),
                ('university', models.CharField(max_length=255)),
                ('departement', models.CharField(max_length=255)),
                ('carear_year', models.IntegerField()),
                ('grad_undergrad', models.CharField(max_length=255)),
                ('description', models.CharField(default=False, max_length=600)),
            ],
        ),
    ]
