# Generated by Django 5.1.6 on 2026-03-20 11:05

import django.db.models.deletion
import exam_ai.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=255)),
                ('student_email', models.EmailField(max_length=254)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('total_score', models.FloatField(blank=True, null=True)),
                ('graded', models.BooleanField(default=False)),
                ('time_taken_seconds', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'exam_ai_submissions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=exam_ai.models.document_upload_path)),
                ('file_type', models.CharField(choices=[('PDF', 'PDF File'), ('DOCX', 'Word Document'), ('TXT', 'Text File')], max_length=4)),
                ('extracted_text', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('total_pages', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'exam_ai_documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('chapter_type', models.CharField(choices=[('UNIT', 'Unit'), ('CHAPTER', 'Chapter'), ('LESSON', 'Lesson'), ('SECTION', 'Section'), ('PART', 'Part'), ('MODULE', 'Module')], default='CHAPTER', max_length=10)),
                ('chapter_number', models.CharField(blank=True, max_length=50)),
                ('start_page', models.IntegerField(blank=True, null=True)),
                ('end_page', models.IntegerField(blank=True, null=True)),
                ('start_line', models.IntegerField(blank=True, null=True)),
                ('end_line', models.IntegerField(blank=True, null=True)),
                ('content_preview', models.TextField(blank=True)),
                ('full_content', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='exam_ai.document')),
            ],
            options={
                'db_table': 'exam_ai_chapters',
                'ordering': ['chapter_number', 'start_page'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('answer', models.TextField()),
                ('question_type', models.CharField(choices=[('MCQ', 'Multiple Choice'), ('SHORT', 'Short Answer'), ('LONG', 'Long Answer'), ('TRUE_FALSE', 'True/False'), ('FILL_BLANK', 'Fill in the Blank'), ('MATCHING', 'Matching'), ('CALCULATION', 'Calculation'), ('ESSAY', 'Essay'), ('DIAGRAM', 'Diagram Based'), ('CASE_STUDY', 'Case Study'), ('NUMERICAL', 'Numerical Problem'), ('DERIVATION', 'Derivation'), ('PROOF', 'Proof'), ('ANALYSIS', 'Analysis'), ('COMPREHENSION', 'Comprehension')], default='SHORT', max_length=15)),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], default='MEDIUM', max_length=6)),
                ('options', models.JSONField(blank=True, null=True)),
                ('topic', models.CharField(blank=True, max_length=100)),
                ('subtopic', models.CharField(blank=True, max_length=100)),
                ('page_number', models.IntegerField(blank=True, null=True)),
                ('line_number', models.IntegerField(blank=True, null=True)),
                ('time_estimate_seconds', models.IntegerField(default=60)),
                ('marks', models.IntegerField(default=10)),
                ('requires_calculation', models.BooleanField(default=False)),
                ('requires_diagram', models.BooleanField(default=False)),
                ('formula_needed', models.TextField(blank=True)),
                ('hints', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='exam_ai.chapter')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exam_ai.document')),
            ],
            options={
                'db_table': 'exam_ai_questions',
                'ordering': ['chapter', 'page_number', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('page_number', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exam_ai.chapter')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='exam_ai.document')),
                ('related_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exam_ai.question')),
            ],
            options={
                'db_table': 'exam_ai_examples',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answer_text', models.TextField(blank=True)),
                ('answer_image', models.ImageField(blank=True, null=True, upload_to=exam_ai.models.answer_image_upload_path)),
                ('score', models.FloatField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exam_ai.examsubmission')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_answers', to='exam_ai.question')),
            ],
            options={
                'db_table': 'exam_ai_answers',
            },
        ),
        migrations.CreateModel(
            name='TempExam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('duration_minutes', models.IntegerField()),
                ('total_questions', models.IntegerField()),
                ('total_marks', models.IntegerField()),
                ('selected_chapters', models.JSONField(default=list)),
                ('chapter_range_text', models.CharField(blank=True, max_length=255)),
                ('difficulty_breakdown', models.JSONField(default=dict)),
                ('type_breakdown', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_exams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'exam_ai_temp_exams',
            },
        ),
        migrations.AddField(
            model_name='examsubmission',
            name='temp_exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='exam_ai.tempexam'),
        ),
        migrations.CreateModel(
            name='TempExamQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.IntegerField()),
                ('marks', models.IntegerField(default=10)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_ai.question')),
                ('temp_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exam_ai.tempexam')),
            ],
            options={
                'db_table': 'exam_ai_temp_exam_questions',
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='chapter',
            index=models.Index(fields=['document', 'chapter_number'], name='exam_ai_cha_documen_42a635_idx'),
        ),
        migrations.AddIndex(
            model_name='chapter',
            index=models.Index(fields=['start_page', 'end_page'], name='exam_ai_cha_start_p_b09844_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['document', 'chapter'], name='exam_ai_que_documen_c2438f_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['question_type', 'difficulty'], name='exam_ai_que_questio_ee48f7_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['topic'], name='exam_ai_que_topic_8480ad_idx'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['submission', 'graded_at'], name='exam_ai_ans_submiss_a3a0a9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('submission', 'question')},
        ),
        migrations.AddIndex(
            model_name='tempexam',
            index=models.Index(fields=['user', 'expires_at'], name='exam_ai_tem_user_id_bc476e_idx'),
        ),
        migrations.AddIndex(
            model_name='tempexam',
            index=models.Index(fields=['is_active'], name='exam_ai_tem_is_acti_d2d447_idx'),
        ),
        migrations.AddIndex(
            model_name='examsubmission',
            index=models.Index(fields=['temp_exam', 'student_email'], name='exam_ai_sub_temp_ex_d724ab_idx'),
        ),
        migrations.AddIndex(
            model_name='examsubmission',
            index=models.Index(fields=['graded'], name='exam_ai_sub_graded_41fc0e_idx'),
        ),
        migrations.AddIndex(
            model_name='tempexamquestion',
            index=models.Index(fields=['temp_exam', 'order'], name='exam_ai_tem_temp_ex_841c7f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tempexamquestion',
            unique_together={('temp_exam', 'question')},
        ),
    ]
