# Generated by Django 5.1.6 on 2026-03-28 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_ai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file_type',
            field=models.CharField(choices=[('PDF', 'PDF File'), ('DOCX', 'Word Document'), ('TXT', 'Text File'), ('JPG', 'JPEG Image'), ('PNG', 'PNG Image'), ('GIF', 'GIF Image'), ('BMP', 'BMP Image'), ('TIFF', 'TIFF Image'), ('WEBP', 'WebP Image')], max_length=4),
        ),
    ]
