# Generated by Django 5.1.6 on 2026-04-07 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_id', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=500)),
                ('source', models.CharField(choices=[('oer', 'OER Commons'), ('mit', 'MIT OpenCourseWare'), ('other', 'Other')], max_length=20)),
                ('content_type', models.CharField(choices=[('presentation', 'PowerPoint'), ('lecture', 'Lecture Notes'), ('video', 'Video Lecture'), ('pdf', 'PDF Document')], default='presentation', max_length=20)),
                ('embed_url', models.URLField(max_length=1000)),
                ('source_url', models.URLField(max_length=1000)),
                ('thumbnail', models.URLField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('author', models.CharField(blank=True, max_length=200)),
                ('course_code', models.CharField(blank=True, max_length=100)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_educational_content', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-saved_at'],
                'unique_together': {('user', 'content_id')},
            },
        ),
    ]
