# Generated by Django 6.0.2 on 2026-03-12 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AnnouncerName', models.CharField(max_length=100)),
                ('AnnouncerPosition', models.CharField(max_length=100)),
                ('AnnouncementSubject', models.CharField(max_length=200)),
                ('AnnouncementBody', models.CharField(max_length=600)),
                ('AnnouncerEmail', models.EmailField(max_length=254)),
            ],
        ),
    ]
