# Generated by Django 6.0.2 on 2026-03-12 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('writterEmail', models.EmailField(max_length=255)),
                ('bodyImageLink', models.FileField(default=False, upload_to='')),
                ('bodyVidioLink', models.FileField(default=False, max_length=2080, upload_to='')),
                ('country', models.CharField(default=False, max_length=255)),
                ('university', models.CharField(max_length=255)),
                ('departement', models.CharField(max_length=255)),
                ('carear_year', models.IntegerField()),
                ('grad_undergrad', models.CharField(max_length=255)),
                ('description', models.CharField(default=False, max_length=600)),
            ],
        ),
    ]
