# Generated by Django 5.1.6 on 2026-03-28 09:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'marriage_mystery_category',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FacialProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.UUIDField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('detected_gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('gender_confidence', models.FloatField(default=0)),
                ('eye_size', models.FloatField(default=0)),
                ('eyebrow_thickness', models.FloatField(default=0)),
                ('nose_length', models.FloatField(default=0)),
                ('nose_width', models.FloatField(default=0)),
                ('lip_size', models.FloatField(default=0)),
                ('chin_prominence', models.FloatField(default=0)),
                ('face_shape', models.FloatField(default=0)),
                ('facial_fullness', models.FloatField(default=0)),
                ('skin_tone', models.FloatField(default=0)),
                ('lip_color', models.FloatField(default=0)),
                ('hair_color', models.FloatField(default=0)),
                ('forehead_lines', models.FloatField(default=0)),
                ('beard_fullness', models.FloatField(default=0)),
                ('hair_type', models.FloatField(default=0)),
                ('ear_visibility', models.FloatField(default=0)),
                ('smile_intensity', models.FloatField(default=0)),
                ('perceived_confidence', models.FloatField(default=0)),
                ('perceived_kindness', models.FloatField(default=0)),
                ('eyebrow_arch', models.FloatField(default=0)),
                ('eye_spacing', models.FloatField(default=0)),
                ('jaw_definition', models.FloatField(default=0)),
                ('extraction_successful', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'marriage_mystery_facial_profile',
            },
        ),
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.UUIDField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model_score', models.FloatField()),
                ('chance_score', models.FloatField()),
                ('final_score', models.FloatField()),
                ('verdict', models.CharField(choices=[('MATCH', 'Match'), ('NO_MATCH', 'No Match')], max_length=10)),
                ('is_match', models.BooleanField()),
                ('user_gender', models.CharField(blank=True, max_length=1)),
                ('detected_gender', models.CharField(blank=True, max_length=1)),
                ('same_gender_penalty_applied', models.BooleanField(default=False)),
                ('gender_penalty_amount', models.FloatField(default=0)),
                ('facial_features', models.JSONField(default=dict)),
                ('behavioral_answers', models.JSONField(default=dict)),
                ('feature_alignment', models.JSONField(default=dict)),
                ('cosmic_message', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marriage_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'marriage_mystery_match_result',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('facial_feature', models.CharField(help_text='Maps to facial feature field name', max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='marriage_mystery.category')),
            ],
            options={
                'db_table': 'marriage_mystery_question',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AnswerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('value', models.IntegerField(help_text='0-100 scale value')),
                ('order', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='marriage_mystery.question')),
            ],
            options={
                'db_table': 'marriage_mystery_answer_option',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UserResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marriage_mystery.question')),
                ('selected_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marriage_mystery.answeroption')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'marriage_mystery_user_response',
                'unique_together': {('session_id', 'question')},
            },
        ),
    ]
