# Generated by Django 6.0.2 on 2026-03-12 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('id_no', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('university', models.CharField(max_length=255)),
                ('departement', models.CharField(max_length=255)),
                ('carear_year', models.IntegerField()),
                ('grad_undergrad', models.CharField(max_length=255)),
                ('Precence', models.CharField(max_length=1)),
            ],
        ),
    ]
