# Generated by Django 6.0.2 on 2026-03-12 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassToEnroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fallOrSpring', models.CharField(max_length=255)),
                ('description', models.CharField(default=False, max_length=600)),
                ('Departement', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(default=False, max_length=2083)),
                ('credit_hour', models.IntegerField()),
                ('instructor', models.CharField(default=False, max_length=255)),
                ('ects', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(default=False, max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(default=False, max_length=2083)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(default=False, max_length=600)),
                ('din', models.CharField(default=False, max_length=255)),
                ('councelor', models.CharField(default=False, max_length=255)),
            ],
        ),
    ]
