# Generated by Django 5.1.6 on 2026-04-07 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('requirements', models.TextField()),
                ('type', models.CharField(choices=[('internship', 'Internship'), ('job', 'Job')], max_length=20)),
                ('location', models.CharField(max_length=200)),
                ('salary_range', models.CharField(blank=True, max_length=100)),
                ('requires_resume', models.BooleanField(default=True)),
                ('requires_essay', models.BooleanField(default=False)),
                ('requires_additional_docs', models.BooleanField(default=False)),
                ('application_deadline', models.DateTimeField()),
                ('response_deadline_days', models.IntegerField(default=7)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('filled', 'Filled'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_jobs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
