# Generated by Django 6.0.2 on 2026-03-12 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='user_images/')),
                ('id_no', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('university', models.CharField(blank=True, max_length=255, null=True)),
                ('student_or_instractor', models.CharField(blank=True, choices=[('student', 'Student'), ('instructor', 'Instructor')], max_length=255, null=True)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('career_year', models.IntegerField(blank=True, null=True)),
                ('grad_undergrad', models.CharField(blank=True, choices=[('graduate', 'Graduate'), ('undergraduate', 'Undergraduate')], max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=600, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
