# Generated by Django 5.1.6 on 2026-03-30 17:13

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_library', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doab_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('handle', models.CharField(blank=True, help_text='DOI/Handle', max_length=200)),
                ('title', models.CharField(db_index=True, max_length=500)),
                ('subtitle', models.CharField(blank=True, max_length=500)),
                ('authors', models.JSONField(default=list, help_text='List of authors')),
                ('subjects', models.JSONField(default=list, help_text='List of subject classifications')),
                ('publisher', models.CharField(blank=True, db_index=True, max_length=300)),
                ('publication_date', models.CharField(blank=True, max_length=50)),
                ('language', models.CharField(db_index=True, default='en', max_length=10)),
                ('abstract', models.TextField(blank=True)),
                ('table_of_contents', models.TextField(blank=True)),
                ('pdf_url', models.URLField(blank=True, max_length=500)),
                ('epub_url', models.URLField(blank=True, max_length=500)),
                ('html_url', models.URLField(blank=True, max_length=500)),
                ('cover_url', models.URLField(blank=True, max_length=500)),
                ('license_info', models.CharField(blank=True, max_length=200)),
                ('rights', models.TextField(blank=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('view_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_cached', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_by', to='digital_library.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bookmark',
                'verbose_name_plural': 'Bookmarks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookRating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='digital_library.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Book Rating',
                'verbose_name_plural': 'Book Ratings',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('books', models.ManyToManyField(blank=True, related_name='categories', to='digital_library.book')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='digital_library.category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(help_text='Short code like ME, EE, CS', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='📖', help_text='Emoji icon', max_length=10)),
                ('search_terms', models.TextField(help_text='Comma-separated search terms for DOAB API')),
                ('default_limit', models.IntegerField(default=20, help_text='Default number of books to fetch')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['faculty', 'display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DownloadHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('format_type', models.CharField(choices=[('pdf', 'PDF'), ('epub', 'EPUB'), ('html', 'HTML')], max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Download History',
                'verbose_name_plural': 'Download Histories',
                'ordering': ['-downloaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('code', models.CharField(help_text='Short code like ENG, SCI, MED', max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='📚', help_text='Emoji icon', max_length=10)),
                ('color', models.CharField(default='blue', help_text='Theme color', max_length=50)),
                ('cover_image', models.URLField(blank=True, max_length=500)),
                ('logo', models.URLField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Faculty',
                'verbose_name_plural': 'Faculties',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ReadingHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_page', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_pages', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('progress_percent', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('last_read', models.DateTimeField(auto_now=True)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Reading History',
                'verbose_name_plural': 'Reading Histories',
                'ordering': ['-last_read'],
            },
        ),
        migrations.CreateModel(
            name='RecentView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Recent View',
                'verbose_name_plural': 'Recent Views',
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.FloatField(default=0.0, help_text='Recommendation score')),
                ('reason', models.CharField(blank=True, help_text='Why this book was recommended', max_length=200)),
                ('is_viewed', models.BooleanField(default=False)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Recommendation',
                'verbose_name_plural': 'Recommendations',
                'ordering': ['-score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query', models.CharField(db_index=True, max_length=500)),
                ('result_count', models.IntegerField(default=0)),
                ('search_type', models.CharField(choices=[('general', 'General'), ('subject', 'By Subject'), ('publisher', 'By Publisher'), ('author', 'By Author'), ('title', 'By Title')], default='general', max_length=50)),
                ('filters', models.JSONField(blank=True, default=dict, help_text='Applied filters')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('searched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Search History',
                'verbose_name_plural': 'Search Histories',
                'ordering': ['-searched_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('default_format', models.CharField(choices=[('pdf', 'PDF'), ('epub', 'EPUB'), ('html', 'HTML')], default='pdf', max_length=10)),
                ('items_per_page', models.IntegerField(choices=[(10, '10'), (20, '20'), (50, '50'), (100, '100')], default=20)),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('auto', 'Auto')], default='light', max_length=20)),
                ('email_notifications', models.BooleanField(default=True)),
                ('new_books_alert', models.BooleanField(default=False)),
                ('last_active', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Preference',
                'verbose_name_plural': 'User Preferences',
            },
        ),
        migrations.DeleteModel(
            name='GeneralMaterial',
        ),
        migrations.DeleteModel(
            name='LessonMaterial',
        ),
        migrations.DeleteModel(
            name='vidios',
        ),
        migrations.AddField(
            model_name='book',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='books', to='digital_library.department'),
        ),
        migrations.AddField(
            model_name='downloadhistory',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='digital_library.book'),
        ),
        migrations.AddField(
            model_name='downloadhistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='faculty',
            index=models.Index(fields=['code'], name='digital_lib_code_10616e_idx'),
        ),
        migrations.AddIndex(
            model_name='faculty',
            index=models.Index(fields=['is_active'], name='digital_lib_is_acti_0c74ba_idx'),
        ),
        migrations.AddField(
            model_name='department',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='digital_library.faculty'),
        ),
        migrations.AddField(
            model_name='readinghistory',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digital_library.book'),
        ),
        migrations.AddField(
            model_name='readinghistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recentview',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digital_library.book'),
        ),
        migrations.AddField(
            model_name='recentview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recent_views', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_to', to='digital_library.book'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='searches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='favorite_departments',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='digital_library.department'),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='library_preferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='bookmark',
            index=models.Index(fields=['user', 'created_at'], name='digital_lib_user_id_a30281_idx'),
        ),
        migrations.AddIndex(
            model_name='bookmark',
            index=models.Index(fields=['book'], name='digital_lib_book_id_8ffbe0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together={('user', 'book')},
        ),
        migrations.AddIndex(
            model_name='bookrating',
            index=models.Index(fields=['book', '-created_at'], name='digital_lib_book_id_b9022b_idx'),
        ),
        migrations.AddIndex(
            model_name='bookrating',
            index=models.Index(fields=['rating'], name='digital_lib_rating_3c6d2c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bookrating',
            unique_together={('user', 'book')},
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug'], name='digital_lib_slug_3c9d5a_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_active'], name='digital_lib_is_acti_8ca61d_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['title'], name='digital_lib_title_fc5cae_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['publisher'], name='digital_lib_publish_4d8b7a_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['language'], name='digital_lib_languag_67c1f8_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['doab_id'], name='digital_lib_doab_id_ba5b8d_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['is_featured'], name='digital_lib_is_feat_73dedf_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['-view_count'], name='digital_lib_view_co_36e4cb_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['created_at'], name='digital_lib_created_a5b388_idx'),
        ),
        migrations.AddIndex(
            model_name='downloadhistory',
            index=models.Index(fields=['user', '-downloaded_at'], name='digital_lib_user_id_e44f91_idx'),
        ),
        migrations.AddIndex(
            model_name='downloadhistory',
            index=models.Index(fields=['book', '-downloaded_at'], name='digital_lib_book_id_522210_idx'),
        ),
        migrations.AddIndex(
            model_name='downloadhistory',
            index=models.Index(fields=['downloaded_at'], name='digital_lib_downloa_15f900_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['faculty', 'code'], name='digital_lib_faculty_3fc961_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['is_active'], name='digital_lib_is_acti_90b3c8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('faculty', 'code')},
        ),
        migrations.AddIndex(
            model_name='readinghistory',
            index=models.Index(fields=['user', '-last_read'], name='digital_lib_user_id_467dda_idx'),
        ),
        migrations.AddIndex(
            model_name='readinghistory',
            index=models.Index(fields=['progress_percent'], name='digital_lib_progres_15e99e_idx'),
        ),
        migrations.AddIndex(
            model_name='readinghistory',
            index=models.Index(fields=['completed'], name='digital_lib_complet_c2b6e5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='readinghistory',
            unique_together={('user', 'book')},
        ),
        migrations.AddIndex(
            model_name='recentview',
            index=models.Index(fields=['user', '-viewed_at'], name='digital_lib_user_id_5e3407_idx'),
        ),
        migrations.AddIndex(
            model_name='recentview',
            index=models.Index(fields=['viewed_at'], name='digital_lib_viewed__25c504_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='recentview',
            unique_together={('user', 'book')},
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['user', '-score'], name='digital_lib_user_id_0910db_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['is_viewed'], name='digital_lib_is_view_ca866c_idx'),
        ),
        migrations.AddIndex(
            model_name='searchhistory',
            index=models.Index(fields=['user', '-searched_at'], name='digital_lib_user_id_dbd217_idx'),
        ),
        migrations.AddIndex(
            model_name='searchhistory',
            index=models.Index(fields=['query'], name='digital_lib_query_47e7bc_idx'),
        ),
        migrations.AddIndex(
            model_name='searchhistory',
            index=models.Index(fields=['searched_at'], name='digital_lib_searche_76640b_idx'),
        ),
        migrations.AddIndex(
            model_name='searchhistory',
            index=models.Index(fields=['search_type'], name='digital_lib_search__97499a_idx'),
        ),
    ]
