# Generated by Django 5.1.6 on 2026-03-31 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_library', '0003_alter_bookrating_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='search_count',
        ),
        migrations.RemoveField(
            model_name='department',
            name='search_terms',
        ),
        migrations.AddField(
            model_name='department',
            name='search_subjects',
            field=models.TextField(default='General,Engineering,Science,Mathematics,Physics,Chemistry,Biology', help_text='Comma-separated subject terms for DOAB API'),
            preserve_default=False,
        ),
    ]
